-- MySQL Script generated by MySQL Workbench
-- ter 04 mai 2021 16:34:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema agladev
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema agladev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agladev` DEFAULT CHARACTER SET utf8 ;
USE `agladev` ;

-- -----------------------------------------------------
-- Table `agladev`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agladev`.`Usuario` (
  `usuarioCod` INT NOT NULL AUTO_INCREMENT,
  `usuarioNome` VARCHAR(100) NOT NULL,
  `usuarioSobrenome` VARCHAR(100) NOT NULL,
  `usuarioEmail` VARCHAR(255) NOT NULL,
  `usuarioSenha` VARCHAR(255) NOT NULL,
  `usuarioDataCadastro` TIMESTAMP NOT NULL DEFAULT  CURRENT_TIMESTAMP,
  `usuarioImg` VARCHAR(255) NULL,
  PRIMARY KEY (`usuarioCod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agladev`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agladev`.`Cliente` (
  `usuarioCod` INT NOT NULL,
  PRIMARY KEY (`usuarioCod`),
  INDEX `fk_Cliente_Usuario1_idx` (`usuarioCod` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Usuario1`
    FOREIGN KEY (`usuarioCod`)
    REFERENCES `agladev`.`Usuario` (`usuarioCod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agladev`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agladev`.`Funcionario` (
  `usuarioCod` INT NOT NULL,
  INDEX `fk_Funcionario_Usuario1_idx` (`usuarioCod` ASC) VISIBLE,
  PRIMARY KEY (`usuarioCod`),
  CONSTRAINT `fk_Funcionario_Usuario1`
    FOREIGN KEY (`usuarioCod`)
    REFERENCES `agladev`.`Usuario` (`usuarioCod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agladev`.`CategoriaProjeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agladev`.`CategoriaProjeto` (
  `categoriaProjetoCod` INT NOT NULL AUTO_INCREMENT,
  `categoriaProjetoNome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`categoriaProjetoCod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agladev`.`Projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agladev`.`Projeto` (
  `projetoCod` INT NOT NULL AUTO_INCREMENT,
  `projetoTitulo` VARCHAR(100) NOT NULL,
  `projetoDescricao` VARCHAR(512) NULL,
  `projetoDataInicio` DATE NOT NULL,
  `projetoDataConclusao` DATE NOT NULL,
  `cliente_usuarioCod` INT NOT NULL,
  `funcionario_usuarioCod` INT NOT NULL,
  `categoriaProjetoCod` INT NOT NULL,
  PRIMARY KEY (`projetoCod`, `categoriaProjetoCod`),
  INDEX `fk_Projeto_Cliente1_idx` (`cliente_usuarioCod` ASC) VISIBLE,
  INDEX `fk_Projeto_Funcionario1_idx` (`funcionario_usuarioCod` ASC) VISIBLE,
  INDEX `fk_Projeto_CategoriaProjeto1_idx` (`categoriaProjetoCod` ASC) VISIBLE,
  CONSTRAINT `fk_Projeto_Cliente1`
    FOREIGN KEY (`cliente_usuarioCod`)
    REFERENCES `agladev`.`Cliente` (`usuarioCod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Projeto_Funcionario1`
    FOREIGN KEY (`funcionario_usuarioCod`)
    REFERENCES `agladev`.`Funcionario` (`usuarioCod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Projeto_CategoriaProjeto1`
    FOREIGN KEY (`categoriaProjetoCod`)
    REFERENCES `agladev`.`CategoriaProjeto` (`categoriaProjetoCod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agladev`.`EtapaProjeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agladev`.`EtapaProjeto` (
  `etapaProjetoCod` INT NOT NULL AUTO_INCREMENT,
  `etapaProjetoInicio` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `etapaProjetoFim` DATETIME NOT NULL,
  `etapaProjetoDescricao` VARCHAR(512) NOT NULL,
  `projetoCod` INT NOT NULL,
  PRIMARY KEY (`etapaProjetoCod`, `projetoCod`),
  INDEX `fk_EtapaProjeto_Projeto1_idx` (`projetoCod` ASC) VISIBLE,
  CONSTRAINT `fk_EtapaProjeto_Projeto1`
    FOREIGN KEY (`projetoCod`)
    REFERENCES `agladev`.`Projeto` (`projetoCod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;





-- INSERTS
# Pessoa
INSERT INTO Usuario VALUES 
(NULL,'José','Aglailson','jose@gmail.com','123',DEFAULT,'img/perfil/jose.jpg'),
(NULL,'Alana','Lays','al@gmail.com','456',DEFAULT,'img/perfil/alana.jpg'),
(NULL,'Marcos','Silva','ms@gmail.com','543',DEFAULT,'img/perfil/marcos.jpg'),
(NULL,'Bruno','Silva','bs@gmail.com','678',DEFAULT,'img/perfil/bruno.jpg');

SELECT * FROM Usuario;

# Setor
INSERT INTO Setor VALUES
(NULL,'Gerencia', 'É o primeiro setor da empresa'),
(NULL,'Administrativo','Responsável pela administração da empresa'),
(NULL, 'Financeiro', 'Responsável por controla contas, e á receber da empresa'),
(NULL,'Recursos Humanos', 'Trats dos assuntos relacionados aos funcionários'),
(NULL, 'Técnolia da informação', 'Setor responsável pela tecnologia da empresa'),
(NULL, 'Comercial', 'Vende as idéas e produtos da empresa');

SELECT * FROM Setor;

SELECT S.setorNome as 'Setor', C.cargoNome as 'Cargo' FROM Setor S
INNER JOIN Cargo C
ON S.setorCod = C.setorCod;

# Cargo
INSERT INTO Cargo VALUES
(NULL,'Engenheiro de software','Responsável pela empresa','15000',5),
(NULL, 'Recrutador', 'Responsavel por recrutar novos funcionários','3500',4),
(NULL, 'Vendedor', 'Responsavel pela a venda dos sistema','2500',6),
(NULL, 'Programador Backend', 'Desenvolve a parte back de sistema','4000',5);

SELECT * FROM Cargo;

SELECT C.cargoNome , S.setorNome  FROM Cargo C
INNER JOIN Setor S
ON C.setorCod = S.setorCod;


# Funcionario
INSERT INTO Funcionario VALUES
(1,2),
(2,2),
(4,4),
(3,3);

SELECT * FROM Funcionario;
 
SELECT CONCAT(U.usuarioNome," ",U.usuarioSobrenome) AS 'Nome', S.setorNome AS 'Setor', C.cargoNome AS 'Cargo', C.cargoSalario AS 'Sálario' FROM  Funcionario F
INNER JOIN Usuario U ON F.usuarioCod = U.usuarioCod
INNER JOIN Cargo C ON C.cargoCod = F.cargoCod
INNER JOIN Setor S ON S.setorCod = C.setorCod;

# Cliente
INSERT INTO Usuario VALUES 
(NULL,'Bralux','Tintas','bralux@gmail.com','456',DEFAULT,'img/perfil/bralux.jpg'),
(NULL, 'Roberto', 'Alencar','rl@gmail.com','345', DEFAULT, 'img/perfil/roberto.jpg');

INSERT INTO Cliente VALUES
(5),
(6);

SELECT  CONCAT(U.usuarioNome," ",U.usuarioSobrenome) AS 'Nome', U.usuarioEmail AS 'Email' FROM Cliente C
INNER JOIN Usuario U
ON C.usuarioCod = U.usuarioCod;


# Projeto
INSERT INTO Projeto VALUES
(NULL, 'Site Bralux','Desenvolvimento de site institucional','2021-07-01','2021-09-23',5),
(NULL, 'Sistema Emissor de nfe','Sitema para emissão de notas fiscais','2021-03-24','2021-05-21',6);

SELECT * FROM Projeto;

# EtapaProjeto

INSERT INTO EtapaProjeto VALUES
(NULL, DEFAULT, '2021-10-21','Fim do desenvolvimento do modulo de pagamento',1),
(NULL, DEFAULT, '2021-03-13','Inicio do projeto',2);

SELECT U.usuarioNome AS 'Cliente', P.projetoTitulo AS 'Projeto',EP.etapaProjetoDescricao AS 'Etapa', EP.etapaProjetoInicio AS 'Inicio etapa', EP.etapaProjetoFim AS 'Fim etapa' FROM Projeto P
INNER JOIN Usuario U
ON P.usuarioCod = U.usuarioCod
INNER JOIN EtapaProjeto EP
ON P.projetoCod = EP.projetoCod;





